### ISSUE TITLE
kraken2-build can't download things

### ISSUE THREAD

**Issue by fanninpm** [StaPH-B/docker-builds#183]
I've done a bit of investigation, and it seems I've stumbled upon two separate (but related) issues:

1. `kraken2-build`, like `kraken-build`, depends on `rsync` if it's not explicitly told to use FTP. However, the Dockerfile for kraken2 doesn't download `rsync`. When following the instructions from [the kraken2 manual](https://github.com/DerrickWood/kraken2/wiki/Manual) to create the standard Kraken 2 database, kraken2 complains that it can't find rsync (this occurs when it's trying to download anything). The obvious workaround would be to pass the `--use-ftp` flag to kraken2 until this gets resolved; however, this workaround eventually fails with the next issue:
2. `kraken2-build` calls `rsync_from_ncbi.pl` when run with `--use-ftp` (this happens when it's trying to download a reference library), but that script complains that it `Can't locate Getopt/Std.pm in @INC (you may need to install the Getopt::Std module)`. This module is apparently not included in Docker's default Ubuntu Xenial image.

For both of these issues, I noticed that someone encountered a similar problem with the first version of kraken, which brought about the changes in 52e1a76. In particular, `rsync` and `cpanminus` were added as `apt-get` dependencies, and `cpanm` was used to retrieve `Getopt::Std`. Would it make sense to make similar changes to the kraken2 Dockerfiles?

**Comment by kapsakcj** [comment]
Hi @fanninpm , nice catch! Thanks for reporting these issues. 

I'd be happy to add these dependencies to the kraken2 dockerfiles, at least to the kraken2 dockerfiles that **do not** include a database.

 I'd prefer to not touch the dockerfiles that do download a database because @erinyoung reported today that one of the db's is no longer being hosted: specifically the db included with this one https://github.com/StaPH-B/docker-builds/blob/master/kraken2/2.0.8-beta_hv/Dockerfile . So if we re-build that image, it would throw an error that it can't find the db anymore.

I'll do some testing locally on my machine and see if we can get new docker images up on dockerhub with those tools added.

**Comment by kapsakcj** [comment]
These docker image tags under `staphb/kraken2` docker image repo are currently being rebuilt with the new dependencies `rsync` `cpanminus` and `Getopt::Std`. Please give one a try and let me know how it goes. It seemed to work fine for kraken1, but perhaps there is a perl module missing or something. We can adjust further if necessary.

```bash
2.0.8-beta-no-db
2.0.9-beta-no-db
2.1.0-no-db
2.1.1-no-db
latest  # latest tag uses dockerfile from kraken2/2.1.1-no-db/Dockerfile
```

**Comment by kapsakcj** [comment]
that was quick, they are all available on dockerhub now: https://hub.docker.com/r/staphb/kraken2/tags?page=1&ordering=last_updated

**Comment by fanninpm** [comment]
Both problems are now alleviated. Thanks for the help!
