### ISSUE TITLE
[Container Request]: Webplatform Recommendations

### ISSUE THREAD

**Issue by KingBain** [StaPH-B/docker-builds#408]
### What tool are you looking for and why?

Looking for recommendations for web platforms/web portals that can use these containers to do genomic research.

**Comment by KingBain** [comment]
running the containers locally is always an option but what about a multi user/ multi workload web portal. Ive seen a couple GRDI portals, but was curious to see which work best what was used by the community. If open source options were available .

**Comment by erinyoung** [comment]
I haven't answered, because I'm not sure what your question is.

Generally, these can be used by any system that can use docker containers (or singularity). There are some systems that don't have enough CPUs or RAM to run the tools in the containers, but that's a separate issue. 

I think most of our users are using a linux or mac based command-line.
