### ISSUE TITLE
[Docker Workshop]: Add AMRFinderPlus v. 3.11.2 

### ISSUE THREAD

**Issue by hollygene** [StaPH-B/docker-builds#550]
### What container needs an update?

I know all of these containers are awesome, but...

I would like to add AMRFinderPlus for the Docker workshop (assuming this is okay - not sure if additions are different/harder!).

**Comment by kapsakcj** [comment]
That would be great! I will copy over relevant info from the original GitHub issue #506 below:

OK, a new database (version = `2022-12-19.1`) has been released, I think we should make a new dockerfile.

database & associated files: https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.11/2022-12-19.1/

changelog which describes the update to the database: https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.11/2022-12-19.1/changelog.txt

Here's the overview of changes, importantly the --organism option for klebsiella species and Neisseria species has been split

>Overview: 
    - -o / --organism "Klebsiella" option split to "Klebsiella_pneumoniae" and "Klebsiella_oxytoca"
    - -o / --organism "Neisseria" option split to "Neisseria_gonorrhoeae" and "Neisseria_meningitidis"
    - Berkholderia blaPEN gene symbol reform based on review of Poirel, et al., 2009 (see below for curator explanation)
    - Many refined phenotypes ("class" and "subclasses") based on curation of the literature
    - New Klebsiella, Pseudomonas, and Acinetobacter point mutations

My suggested strategy for this new version of AMRFinderPlus is to:

1. copy & paste the dockerfile for the previous version (3.10.42) to a new subdirectory `/ncbi-amrfinderplus/3.11.2/Dockerfile`
2. update the AMRFinderPlus version on line 3
3. test that the dockerfile & image builds successfully
4. copy & paste the README.md from the previous version to the new version's subdirectory. Also update the output of `amrfinder -l` on the README.md since there are new `--organism` options available now

**Comment by erinyoung** [comment]
This is a great one to work on!

**Comment by kapsakcj** [comment]
Closed via PR #599 

Thanks for the PR, Holly!
