### ISSUE TITLE
[Request An Update]: freyja

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#655]
### What container needs an update?

I tried to use freyja update in singularity, and this was the error I got

```
Read-only file system: '/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/data/curated_lineages.json
```

I would like to propose creating a freyja container weekly (or every so often) and using a tagging system of ${version}-${freyja-update-date}

**Comment by erinyoung** [comment]
To be clear, freyja's lineages update more frequently that freyja itself does.

**Comment by kapsakcj** [comment]
I was able to recreate a similar permission error in docker when running the container as non-root user. When run as `root` user the `freyja update` command ran with no issues.

ICYMI - `freyja update` has an `--outdir` option so that you can write the files to a directory that you have permission to write to. That may be a solution when running the command via singularity.

I'm fine with the proposal of deploying new docker images every 2 weeks, but I would encourage some documentation to explain why there may be a lot of docker image tags available on dockerhub & quay in the future
