### ISSUE TITLE
[Request An Update]: There's a new version of minimap2

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#658]
### What container needs an update?

There's a new version of minimap2

https://github.com/lh3/minimap2/releases/tag/v2.25

**Comment by kapsakcj** [comment]
I'll make a PR for this new version. Thanks for the heads up

**Comment by kapsakcj** [comment]
Closing this issue since v2.25 was added in PR #659 

But I will note that v2.26 was released a few days ago, but in my opinion not worth adding to this repo since the only change was related to the python package (which we don't use in our docker images): https://github.com/lh3/minimap2/compare/v2.25...v2.26
