### ISSUE TITLE
[Request An Update]: raven

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#717]
### What container needs an update?

There's a new version of raven : 1.8.2

All the version release says is "bug fixes" (https://github.com/lbcb-sci/raven/releases/tag/1.8.2)

**Comment by deemalone** [comment]
Oooooo ravens! I'll choose this one for the Docker training! Thanks!

**Comment by erinyoung** [comment]
Perfect!

Ravens are cool, and so is long-read assembly.

**Comment by erinyoung** [comment]
@deemalone , are you still working on this?

**Comment by deemalone** [comment]
Yes! Apologies, it's taking me a while. 
Ran into some issues that I'm trying to figure out.
Unless . . . I'm holding you up?
I won't be offended if you have to cut me loose.
But, yes, I'm still working on it.

**Comment by kapsakcj** [comment]
@deemalone We would be happy to help troubleshoot the issues you're encountering!

I can't speak for Erin, but you're not holding me up 😄 I think she was checking in to see how things are going

**Comment by deemalone** [comment]
Oh, thank goodness! I've taken so long they've released a 1.8.3! 😅

For 1.8.2, I went down a rabbit hole of "compare the code" and "what am I supposed to do again?" when I think all I had to do was switch the version in the dockerfile, no?

I couldn't figure out how to fork (the option seems to be missing at the top of my browser no matter where I navigate) but I downloaded the 1.8.1 dockerfile, changed the version info, uploaded it to my GitHub, pulled it into Gitpod, built an image from the dockerfile, hopped into the container and saw that the ERA-files were generated. So, I think that means it worked . . . I think. 

THEN (for confirmation) I tried using docker build -t old --build-arg="RAVEN_VERSION=1.8.1" . to build an older version of raven and got the same ERA-files which should happen because the test files would be the same in the dockerfile regardless of the version. So, I think that means it worked . . . I think. . . right? 🤔

**Comment by erinyoung** [comment]
> THEN (for confirmation) I tried using docker build -t old --build-arg="RAVEN_VERSION=1.8.1" . to build an older version of raven and got the same ERA-files which should happen because the test files would be the same in the dockerfile regardless of the version. So, I think that means it worked . . . I think. . . right? 🤔

Yes! It is probably working.

You can send me an email to schedule a meeting and you can share your screen to figure out how to fork the github repo.

**Comment by deemalone** [comment]
Sounds good, thanks! I'll send an email soon!

**Comment by erinyoung** [comment]
Closed by https://github.com/StaPH-B/docker-builds/pull/783
