### ISSUE TITLE
[Bug]: samtools v 1.18 plot-ampliconstats not working

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#756]
### What container were you trying to use, and how were you attempting to use it?

This doesn't happen for me, but it does happen to other users who use samtools plot-ampliconstats with the samtools 1.18 container when using singularity. 

### Relevant log output

```shell
gnuplot: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file:
No such file or directory
gnuplot: at /usr/local/bin/plot-ampliconstats line 100.
```

**Comment by kapsakcj** [comment]
I'm not able to reproduce this error with my local `singularity`, we're going to need more information on the setup in order to troubleshoot. Need to know:

- singularity version used
- docker image name & tag used
- how the singularity image was built/pulled from dockerhub/quay
- command used that generates the above error message (I'm guessing `plot-ampliconstats plot ...`)

When I look at the shared libraries from within the singularity image, I can see the one in the error message:

```
Singularity> ldd /usr/bin/gnuplot
        linux-vdso.so.1 (0x00007ffc61dee000)
        libedit.so.2 => /lib/x86_64-linux-gnu/libedit.so.2 (0x00007fea8c0b6000)
        libgd.so.3 => /lib/x86_64-linux-gnu/libgd.so.3 (0x00007fea8c04e000)
        liblua5.4.so.0 => /lib/x86_64-linux-gnu/liblua5.4.so.0 (0x00007fea8c00c000)
        libwx_gtk3u_core-3.0.so.0 => /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0 (0x00007fea8b9ff000)
        libwx_baseu-3.0.so.0 => /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 (0x00007fea8b7d0000)
        libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fea8b7bc000)
        libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fea8b755000)
        libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fea8b6f5000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fea8b5bb000)
        libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fea8b493000)
        libQt5Network.so.5 => /lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fea8b2e2000)
        libQt5Gui.so.5 => /lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fea8ac02000)
        libQt5Core.so.5 => /lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fea8a6a3000)

[remainder of output removed for brevity]
```

and I used the docker image from dockerhub: `staphb/samtools:1.18`

So I'm thinking this is specific to the user's environment & invocation of the command

**Comment by erinyoung** [comment]
The errors are from those using the Cecret workflow, so it's samtools version 1.18 from dockerhub and it was pulled and run by nextflow with autobinding. 

I have qt installed in my environment, which is likely the reason I can't replicate this error either.
